name: Build and Test on MacOS

on:
  push

env:
  PYTHON_VERSION: 3.9

jobs:
  build-and-test-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Initialize Environment
      shell: bash
      run: make init

    - name: Run Tests
      shell: bash
      run: make test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.xml